plugins {
  id "checkstyle"
  id "com.adarshr.test-logger" version "${testLoggerVersion}" apply false
  id "com.diffplug.spotless" version "${spotlessVersion}"
  id "idea"
  id "net.ltgt.errorprone" version "${errorPronePluginVersion}" apply false
  id "org.graalvm.buildtools.native" version "${graalvmBuildtoolsVersion}" apply false
}

group = "dev.gokhun"

allprojects {
  repositories {
    gradlePluginPortal()
    mavenCentral()
  }
}

subprojects {
  apply plugin: "checkstyle"

  checkstyle {
    configFile rootProject.file("checkstyle.xml")
  }

  tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  }
}

spotless {
  java {
    target "lib/src/*/java/**/*.java", "cli/src/*/java/**/*.java"
    importOrder()
    removeUnusedImports()
    cleanthat()
    palantirJavaFormat().style("GOOGLE").formatJavadoc(true)
    formatAnnotations()
  }
  groovyGradle {
    target "*.gradle", "lib/*.gradle", "cli/*.gradle"
    greclipse()
    trimTrailingWhitespace()
    leadingTabsToSpaces(2)
    endWithNewline()
  }
  gherkin {
    target "cli/src/*/resources/**/*.feature"
    gherkinUtils()
  }
  format "misc", {
    target "*.md", ".gitignore", ".gitattributes"
    trimTrailingWhitespace()
    leadingTabsToSpaces(2)
    endWithNewline()
  }
}
