# project
version=0.0.0-SNAPSHOT

# plugins
spotlessVersion=8.10.2
errorPronePluginVersion=5.1.1
graalvmBuildtoolsVersion=1.1.12
testLoggerVersion=4.0.0

# dependencies
guavaVersion=33.7.1-jre
picocliVersion=4.7.7
jacksonVersion=2.22.2
junitVersion=6.1.3
assertjVersion=3.27.7
cucumberVersion=7.34.7
errorProneVersion=2.50.0
errorProneSupportVersion=0.30.0
