name: Build

on:
  push:
    branches: master
  pull_request:

env:
  JAVA_VERSION: '19'
  GRAAL_VERSION: '22.3.1'

jobs:
  build:
    name: 'Build convert on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Add Developer Command Prompt for Microsoft Visual C++'
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: 'Setup GraalVM ${{ env.GRAAL_VERSION }}'
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ env.GRAAL_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-musl: ${{ matrix.os == 'ubuntu-latest' }}
          cache: 'gradle'

      - name: 'Check'
        run: ./gradlew check --no-daemon

      - name: 'Native test'
        run: ./gradlew nativeTest --no-daemon

      - name: 'Native compile'
        run: ./gradlew nativeCompile --no-daemon

      - name: 'Add convert to PATH'
        if: ${{ runner.os != 'Windows' }}
        run: cp ${{ github.workspace }}/build/native/nativeCompile/convert /usr/local/bin/convert

      - name: 'Add convert to PATH'
        if: ${{ runner.os == 'Windows' }}
        run: echo ${{ github.workspace }}\build\native\nativeCompile | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: 'End to end test'
        run: ./gradlew e2e --no-daemon