name: Build

on:
  push:
    branches: main
  pull_request:

env:
  JAVA_VERSION: '19'
  GRAAL_VERSION: '22.3.1'

jobs:
  build:
    name: 'Build convert on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macOS-latest ]

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Setup GraalVM ${{ env.GRAAL_VERSION }}'
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ env.GRAAL_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-musl: ${{ matrix.os == 'ubuntu-latest' }}
          cache: 'gradle'

      - name: 'Check'
        run: ./gradlew check --no-daemon

      - name: 'Native test'
        run: ./gradlew nativeTest --no-daemon

      - name: 'Native compile'
        run: ./gradlew nativeCompile --no-daemon

      - name: 'Compress with UPX'
        if: ${{ runner.os == 'Linux' }}
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            ./build/native/nativeCompile/convert
          args: --best

      - name: 'End to end test'
        run: PATH=$PATH:${{ github.workspace }}/build/native/nativeCompile/convert ./gradlew e2e --no-daemon
