name: Build

on:
  push:
    branches:
     - main
  pull_request:
  merge_group:

env:
  JAVA_VERSION: '25'

jobs:
  build:
    name: 'Build convert on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13 ]

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5

      - name: 'Setup GraalVM ${{ env.GRAAL_VERSION }}'
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: ${{ env.JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-musl: ${{ matrix.os == 'ubuntu-latest' }}
          cache: 'gradle'

      - name: 'Check'
        run: ./gradlew check --no-daemon

      - name: 'Native test'
        run: ./gradlew nativeTest --no-daemon

      - name: 'Native compile'
        run: ./gradlew nativeCompile --no-daemon

      - name: 'Compress with UPX'
        if: ${{ runner.os == 'Linux' }}
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            ./build/native/nativeCompile/convert
          args: --best

      - name: 'Add convert to PATH'
        run: echo "${{ github.workspace }}/build/native/nativeCompile" >> $GITHUB_PATH

      - name: 'End to end test'
        run: ./gradlew e2e --no-daemon
