# TODO Remove this file after jreleaser setup
name: GraalVM Native Image builds
on: [ push, pull_request ]
jobs:
  build:
    name: Build convert on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Check
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              ./gradlew.bat check --stacktrace
          else
              ./gradlew check --stacktrace
          fi
        shell: bash

      - name: Native test
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              ./gradlew.bat nativeTest --stacktrace
          else
              ./gradlew nativeTest --stacktrace
          fi
        shell: bash

      - name: Native compile
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              ./gradlew.bat nativeCompile --stacktrace
          else
              ./gradlew nativeCompile --stacktrace
          fi
        shell: bash