name: Build

on: [ push, pull_request ]

env:
  JAVA_VERSION: '19'
  GRAAL_VERSION: '22.3.1'

jobs:
  build:
    name: 'Build convert on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Add Developer Command Prompt for Microsoft Visual C++'
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: 'Setup GraalVM ${{ env.GRAAL_VERSION }}'
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ env.GRAAL_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: 'gradle'

      - name: 'Check'
        run: ./gradlew check

      - name: 'Native test'
        run: ./gradlew nativeTest

      - name: 'Native compile'
        run: ./gradlew nativeCompile